name: Build Releases

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to build'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - name: Build linux amd64
        run: make pkg/linux_amd64.zip
      - name: Build darwin arm64
        run: make pkg/darwin_arm64.zip
      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: levant-linux-amd64
          path: pkg/linux_amd64.zip
      - name: Upload darwin artifact
        uses: actions/upload-artifact@v4
        with:
          name: levant-darwin-arm64
          path: pkg/darwin_arm64.zip
